### ISSUE TITLE
Attributo Attiva della prestazione

### ISSUE THREAD

**Issue by b3rt4** [damianoazzolini/progettoBasiDiDati#6]
Visto che le cancelliamo, l'attributo "attiva" che significato ha ?

**Comment by damianoazzolini** [comment]
Togliamo quindi attiva dalla prestazione? Direi che questa è la via più veloce

**Comment by b3rt4** [comment]
Va bene

**Comment by damianoazzolini** [comment]
In realtà la prestazione non viene cancellata. In PrestazioneController, la funzione destroy aggiorna il campo attivo della prestazione, ponendolo a 0.

**Comment by b3rt4** [comment]
Allora lasciamo così, non vedendole più visualizzate pensavo che le cancellasse
