### ISSUE TITLE
Campi unique sul database

### ISSUE THREAD

**Issue by b3rt4** [damianoazzolini/progettoBasiDiDati#7]
Nella tabella reparto l'identificativo dovrebbe essere univoco perché l'ho utilizzato in alcuni moduli per identificare univocamente un reparto (tu addirittura hai usato il nome del reparto, nella creazione della prestazione, quindi anche quello dovrebbe essere univoco)
Nella tabella sala dovrebbe essere univoca la coppia nome sala + identificativo reparto perché ammetto che ci siano sale con lo stesso nome solo in reparti diversi.

**Comment by damianoazzolini** [comment]
Ok, quindi nella migration metto:
reparto -> identificativo unique
reparto -> nome unique
sala -> nome + identificativo unique

**Comment by b3rt4** [comment]
Direi di si
